BEGIN;
DROP TRIGGER IF EXISTS trg_sync_optout_suppression ON core.consents;
DROP TRIGGER IF EXISTS trg_stop_followups_on_inbound ON core.interactions;
DROP FUNCTION IF EXISTS ops.sync_optout_suppression();
DROP FUNCTION IF EXISTS ops.stop_followups_on_inbound();
DROP FUNCTION IF EXISTS ops.apply_retention(BOOLEAN);
DROP FUNCTION IF EXISTS ops.fail_delivery(UUID, TEXT);
DROP FUNCTION IF EXISTS ops.complete_delivery(UUID, TEXT);
DROP FUNCTION IF EXISTS ops.claim_delivery(TEXT);
DROP FUNCTION IF EXISTS ops.enqueue_due_followups(TEXT, BOOLEAN);
DROP FUNCTION IF EXISTS ops.followup_is_eligible(UUID);
DROP FUNCTION IF EXISTS ops.check_rate_limit(TEXT, TEXT, INTEGER, INTEGER);
ALTER TABLE core.followups DROP COLUMN IF EXISTS last_error_code;
ALTER TABLE core.followups DROP COLUMN IF EXISTS sent_at;
ALTER TABLE core.followups DROP COLUMN IF EXISTS consent_required;
ALTER TABLE core.followups DROP COLUMN IF EXISTS sequence_number;
DROP TABLE IF EXISTS audit.admin_change_log;
DROP TABLE IF EXISTS ops.optout_suppression;
DROP TABLE IF EXISTS ops.privacy_requests;
DROP TABLE IF EXISTS ops.delivery_outbox;
DROP TABLE IF EXISTS ops.rate_limit_windows;
DELETE FROM ops.runtime_flags WHERE flag_name IN ('followup_enabled', 'dispatcher_enabled', 'retention_enabled', 'automation_paused');
COMMIT;
